version: "3"

services:
    nginx:
        image: nginx:1.25
        ports:
            - 8877:80
        volumes:
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./:/var/www/
        container_name: proj_nginx
        depends_on:
            - app

    app:
        build:
            context: .
            dockerfile: ./_docker/app/Dockerfile
        volumes:
            - ./:/var/www/
        container_name: proj_app
        depends_on:
            - db

    db:
        image: mysql:8.2
        restart: always
        ports:
            - 3306:3306
        volumes:
            - ./tmp/db/:/var/mysql/
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: lar_6
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        container_name: proj_db

